version: '3'
services:
  app:
    build:
      context: ./
    command: bash -c 'php artisan migrate'
    volumes:
      - .:/var/www
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=local
